# Be sure to run yarn build:function in the directory above first
# docker build --build-arg VUE_I18N_PHRASE_VERSION=0.3.4 -t spittal/vue-i18n-phrase:latest -t spittal/vue-i18n-phrase:0.3.4 . && docker push spittal/vue-i18n-phrase

FROM sbvr/node

COPY ./ /home/app/
WORKDIR /home/app/

CMD [ "yarn", "node", "./function/dist/vue-i18n-phrase.umd.js" ]
